name: Build and deploy pages

on:
  push:
    branches: [ "main" ]
    # Löst bei neuen Dateien UND Änderungen in diesen Pfaden aus
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/main.yml"
      # - "scripts/**"
      # - "templates/**"
      # ggf. weitere relevante Pfade ergänzen:
      # - "overrides/**"
      # - "docs/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # gut für MkDocs-Plugins, die Git-Metadaten verwenden

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install mkdocs; fi

      - name: update_banner_counters
        run: python scripts/update_banner_counters.py

      - name: Generate banner stats
        run: |
          python -m pip install pyyaml
          python scripts/make_banner_stats.py --banner-dir docs/banner --out docs/banner/stats.md

      - name: Build MkDocs site
        run: |
          mkdocs build --strict

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
