name: Post ungepostete Banner zu Telegram

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "docs/banner/**"
      #- "scripts/post_banners_to_telegram.py"
      #- "templates/tg_caption_template.txt"

permissions:
  contents: write

jobs:
  post-to-telegram:
    runs-on: ubuntu-latest
    env:
      MAX_POSTS: "5"
      BASE_SITE_URL: "https://r3f1s-on-tour.github.io/banner/"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests

      - name: Poste ungepostete Banner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MAX_POSTS: ${{ env.MAX_POSTS }}
          BASE_SITE_URL: ${{ env.BASE_SITE_URL }}
        run: |
          python scripts/post_banners_to_telegram.py \
          --glob "docs/banner/*.md" \
          --caption-template-file "template/tg_caption_template.txt" \
          --max-posts "${MAX_POSTS}" \
          --base-url "${BASE_SITE_URL}"
      
      - name: Commit & push Änderungen (tg_posted + posted.yml)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/banner/*.md data/posted.yml
          if git diff --cached --quiet; then
            echo "Keine Änderungen zum Commit."
          else
            git commit -m "chore: update posting state (posted.yml, tg_posted)"
            git push
          fi
